{
  config,
  lib,
  machines,
  ...
}:

let
  inherit (lib)
    concatLists
    concatMapStringsSep
    mapAttrsToList
    mkMerge
    mkIf
    listToAttrs
    map
    ;

  forConcat = l: f: concatMapStringsSep "\n" f l;

  datasetMountpointsForChecking = concatLists (
    concatLists (
      mapAttrsToList (
        _: poolConfig:
        mapAttrsToList (
          _: datasetConfig:
          if datasetConfig ? mountpoint && datasetConfig.mountpoint != null then
            [ datasetConfig.mountpoint ]
          else
            [ ]
        ) poolConfig.datasets
      ) config.disko.devices.zpool
    )
  );

  ## Bit of an odd construction: the list above is generated by reading the
  ## disko configuration of the particular host for the datasets (as of May
  ## 2026, Anastasia). At this point, there is no good way for the other
  ## configurations to read this value, so we hardcode it here, but we add an
  ## assertion in the configuration of Anastasia that it is the same list.
  ##
  datasetMountpoints = [
    "/data/pictures"
    "/data/medias"
    "/data/services/nix-cache"
    "/data/services/torrent"
  ];

in
{
  config = mkMerge [
    (mkIf (config.x_niols.isServer && config.x_niols.services.nfs.enabledOnOtherServer) {
      fileSystems = listToAttrs (
        map (datasetMountpoint: {
          name = datasetMountpoint;
          value = {
            device = "${
              machines.servers.${config.x_niols.services.nfs.enabledOn}.internalIp
            }:${datasetMountpoint}";
            fsType = "nfs4";
            options = [
              "hard" # hang until success and return an error if not - better for data integrity - the default
              "_netdev" # this mount requires network - systemd ranks it after `network-online.target`
              "nofail" # boot continues even if the mount fails, rather than going into emergency mode
              "x-systemd.automount" # defer the actual mount until the path is first accessed
              "x-systemd.mount-timeout=10" # give up trying to mount after 10s
            ];
          };
        }) datasetMountpoints
      );
    })

    (mkIf config.x_niols.services.nfs.enabledOnThisServer {
      assertions = [
        {
          assertion = (datasetMountpoints == datasetMountpointsForChecking);
          message = ''
            Hardcoded list of dataset mountpoints does not match the Disko configuration of the host.
              See `nfs.nix` or grep for `datasetMountpoints`.
          '';
        }
      ];

      services.nfs.server = {
        enable = true;

        ## Piggyback on the safety of existing network and allow traffic only from
        ## the internal and local ones.
        ##
        exports = forConcat datasetMountpoints (datasetMountpoint: ''
          ${datasetMountpoint} ${machines.this.internalIp}/24(rw,sync,no_subtree_check)
          ${datasetMountpoint} ${machines.this.localIp}/24(rw,sync,no_subtree_check)
        '');
      };

      ## Allow only NFSv4. It is more secure and has better performance than
      ## NFSv3, but also avoids the need to run rpcbind and rpcidmapd daemons,
      ## which is a bit of a mess.
      ##
      services.nfs.settings.nfsd = {
        vers3 = "no";
        vers4 = "yes";
      };

      networking.firewall.allowedTCPPorts = [ 2049 ];
    })
  ];
}
