{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    nixos-hardware.url = "github:NixOS/nixos-hardware/master";

    flake-parts.url = "github:hercules-ci/flake-parts";

    git-hooks.url = "github:cachix/git-hooks.nix";
    git-hooks.inputs.nixpkgs.follows = "nixpkgs";

    nix-index-database.url = "github:Mic92/nix-index-database";
    nix-index-database.inputs.nixpkgs.follows = "nixpkgs";

    agenix.url = "github:ryantm/agenix";
    agenix.inputs.nixpkgs.follows = "nixpkgs";
    agenix.inputs.darwin.follows = ""; # saves some resources on Linux

    disko.url = "github:nix-community/disko";
    disko.inputs.nixpkgs.follows = "nixpkgs";

    dancelor.url = "github:paris-branch/dancelor";

    emacs-overlay.url = "github:nix-community/emacs-overlay";
    emacs-overlay.inputs.nixpkgs.follows = "nixpkgs";
    emacs-overlay.inputs.nixpkgs-stable.follows = "";
  };

  ## NOTE: This flake must be written as if it was at the root.

  outputs =
    inputs:
    inputs.flake-parts.lib.mkFlake { inherit inputs; } (
      { withSystem, ... }:
      let
        system = "x86_64-linux";
        inherit (inputs.nixpkgs.lib) genAttrs modules;
        pkgs = withSystem system ({ pkgs, ... }: pkgs);
      in
      {
        systems = [ system ];

        flake.nixosConfigurations = genAttrs [ "hello" "cowsay" ] (
          nodeName:
          inputs.nixpkgs.lib.nixosSystem {
            modules = [
              {
                imports = [
                  ./tests/deployment/targetNode.nix
                  (modules.importJSON (./. + "/${nodeName}-network.json")) # generated by nixosTest.nix
                ];
                nixpkgs.hostPlatform = system;
                environment.systemPackages = [ pkgs.${nodeName} ];
              }
            ];
            # specialArgs = specialArgsFor name;
          }
        );

        perSystem =
          {
            system,
            lib,
            pkgs,
            ...
          }:
          {
            _module.args.pkgs = import ./pkgs.nix { inherit inputs system lib; };

            apps.rebuild = {
              type = "app";
              program = "${pkgs.callPackage ./rebuild.nix { flakeRoot = ./.; }}/bin/rebuild";
            };
          };
      }
    );
}
