jobs:
  bump-dancelor:
    name: Bump Dancelor
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: 'access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

            download-attempts = 10 # more than usual because nix-cache might be down

            '
      - id: update
        name: Update flake.lock and create the pull request
        uses: determinatesystems/update-flake-lock@v28
        with:
          branch: dancelor/bump-dancelor
          git-author-email: dancelor@dancelor.org
          git-author-name: Dancelor
          git-committer-email: dancelor@dancelor.org
          git-committer-name: Dancelor
          inputs: dancelor
          pr-title: Bump Dancelor
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        name: Set up auto-merge for the pull request
        run: gh pr merge --auto --squash ${{ steps.update.outputs.pull-request-number }}
name: Bump Dancelor
'on':
  repository_dispatch:
    types:
      - bump-dancelor
  workflow_dispatch: {}
