---

name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

## We specify a concurrency group with automated cancellation. This means that
## other pushes on the same `github.ref` (eg. other pushes to the same pull
## request) cancel previous occurrences of the CI.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  discover:
    name: Discover
    runs-on: ubuntu-latest
    outputs:
      checks: ${{ steps.json.outputs.checks }}
      homeConfigurations: ${{ steps.json.outputs.homeConfigurations }}
      nixosConfigurations: ${{ steps.json.outputs.nixosConfigurations }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            ## Access token to avoid triggering GitHub's rate limiting.
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Gather outputs from the flake
        id: json
        run: |
          {
            if [[ "$GITHUB_REF" =~ ^refs/tags/ ]]; then
              echo >&2 "This CI was triggered by a tag, so only the corresponding home or NixOS configuration will be built."
              echo checks=[]
              if [[ "$GITHUB_REF" =~ ^refs/tags/home-(.+)-on- ]]; then
                echo homeConfigurations="[\"${BASH_REMATCH[1]}\"]"
                echo nixosConfigurations=[]
              elif [[ "$GITHUB_REF" =~ ^refs/tags/nixos-(.+)-gen- ]]; then
                echo homeConfigurations=[]
                echo nixosConfigurations="[\"${BASH_REMATCH[1]}\"]"
              else
                echo >&2 "This is neither a home nor a NixOS configuration, so I do not know what to do."
                exit 2
              fi
            else
              echo >&2 "This CI was not triggered by a tag, so all available checks, home and NixOS configurations will be built."
              read_and_output () {
                printf '%s=' "$1"
                nix eval --impure --raw --expr "
                  with builtins;
                  let flake = getFlake (toString ./.); in
                  toJSON (attrNames flake.$2)
                "
                echo
              }
              read_and_output checks checks.x86_64-linux
              read_and_output homeConfigurations homeConfigurations
              read_and_output nixosConfigurations nixosConfigurations
            fi
          } | tee $GITHUB_OUTPUT

  summarise:
    name: Summarise
    runs-on: ubuntu-latest
    needs:
      - checks
      - homeConfigurations
      - nixosConfigurations
    if: ${{ !cancelled() }}
    steps:
      - name: At least one CI job failed or was cancelled
        if: ${{ needs.checks.result == 'failure' || needs.checks.result == 'cancelled' || needs.homeConfigurations.result == 'failure' || needs.homeConfigurations.result == 'cancelled' || needs.nixosConfigurations.result == 'failure' || needs.nixosConfigurations.result == 'cancelled' }}
        run: false
      - name: All CI jobs succeeded
        run: true

  checks:
    name: Check
    needs: discover
    runs-on: ubuntu-latest
    ## Only run if checks != [], which we test indirectly.
    if: contains(needs.discover.outputs.checks, '"')
    strategy:
      matrix:
        check: ${{ fromJson(needs.discover.outputs.checks) }}
      fail-fast: false
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Get flake inputs and install Attic
        run: nix profile install .#attic
      - name: Set up Attic cache
        uses: ryanccn/attic-action@v0.4
        with:
          endpoint: https://nix-cache.niols.fr/
          cache: nixos-config
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Run check “${{ matrix.check }}”
        run: nix build .#checks.x86_64-linux.${{ matrix.check }} --print-build-logs

  homeConfigurations:
    name: Home
    needs: discover
    runs-on: ubuntu-latest
    ## Only run if homeConfigurations != [], which we test indirectly.
    if: contains(needs.discover.outputs.homeConfigurations, '"')
    strategy:
      matrix:
        home: ${{ fromJson(needs.discover.outputs.homeConfigurations) }}
      fail-fast: false
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        ## NOTE: We build the home configurations as impure because they get
        ## their `home.username` and `home.homeDirectory` from the environment
        ## when they are not used via the Home Manager NixOS module.
      - name: Build Home configuration “${{ matrix.home }}”
        run: nix build .#homeConfigurations.${{ matrix.home }}.activationPackage --impure --print-build-logs

  nixosConfigurations:
    name: NixOS
    needs: discover
    runs-on: ubuntu-latest
    ## Only run if nixosConfigurations != [], which we test indirectly.
    if: contains(needs.discover.outputs.nixosConfigurations, '"')
    strategy:
      matrix:
        nixos: ${{ fromJson(needs.discover.outputs.nixosConfigurations) }}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        ## FIXME: Freeing space takes about 3-4 minutes as of 15 September 2025,
        ## which is lost time on small configurations. It would be nicer if we
        ## could decide whether that is actually necessary.
      - name: Free some extra space
        run: |
          echo 'Available storage before:'
          sudo df -h
          echo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          echo 'Available storage after:'
          sudo df -h
          echo
      - name: Set up emulation layer if necessary
        run: |
          ## NOTE: Orianne is an ARM machine, but the GitHub runners are Intel
          ## machines, so we detect that, install the emulation binaries for
          ## QEMU and tell Nix to behave as an `aarch64-linux` machine.
          system=$(nix eval --impure --raw .#nixosConfigurations.${{ matrix.nixos }}.pkgs.stdenv.hostPlatform.system)
          echo "system = $system" > nix-config
          if [ $system != x86_64-linux ]; then
            printf 'This configuration is a %s, for which we need to install QEMU emulation binaries.\n' "$system"
            sudo apt-get update -y && sudo apt-get install -y qemu-user-static
          fi
      - name: Build NixOS configuration “${{ matrix.nixos }}”
        run: |
          export NIX_CONFIG=$(cat nix-config)
          nix build .#nixosConfigurations.${{ matrix.nixos }}.config.system.build.toplevel --print-build-logs
      - name: Remaining space
        run: |
          echo 'Available storage:'
          sudo df -h
        ## Ideally, we would use the Attic cache for all the CI everywhere.
        ## However, it is not that performant network-wise and it is actually
        ## faster to build the configurations. This is however not true when
        ## deploying, because we need to build the NixOps4 providers, we takes
        ## a lot of time, especially on emulated architectures.
      - name: Install Attic
        run: nix profile install .#attic
      - name: Set up Attic cache if we are going to deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ryanccn/attic-action@v0.4
        with:
          endpoint: https://nix-cache.niols.fr/
          cache: nixos-config
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Deploy NixOps4 resource “${{ matrix.nixos }}” if it exists
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          has_deployment=$(nix eval --impure --raw --expr 'with builtins; if (getFlake (toString ./.)).nixops4Deployments ? ${{ matrix.nixos }} then "true" else "false"')
          if $has_deployment; then
            echo "${{ secrets.DEPLOY_KEY }}" > deploy-key
            chmod 600 deploy-key
            nix develop --command ssh-agent bash -c '
              ssh-add deploy-key
              export NIX_CONFIG=$(cat nix-config)
              nixops4 apply ${{ matrix.nixos }}
            '
          fi
