concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: 'access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

            download-attempts = 10 # more than usual because nix-cache might be down

            '
      - name: Install Attic
        run: nix profile add .#attic
      - name: Set up Attic cache
        uses: ryanccn/attic-action@v0.4.1
        with:
          cache: nixos-config
          endpoint: https://nix-cache.niols.fr/
          token: ${{ secrets.ATTIC_TOKEN }}
      - if: ${{ contains(fromJSON('["orianne"]'), matrix.nixos) }}
        name: Set up emulation layer
        run: 'echo "system = aarch64-linux" > nix-config

          sudo apt-get update -y && sudo apt-get install -y qemu-user-static

          '
      - name: Run check “${{ matrix.check }}”
        run: 'export NIX_CONFIG=$(cat nix-config)

          nix build .#checks.x86_64-linux.${{ matrix.check }} --print-build-logs

          '
    strategy:
      fail-fast: false
      matrix:
        check:
          - deployment
          - pre-commit
  deploy:
    name: Deploy
    needs:
      - nixos
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: 'access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

            download-attempts = 10 # more than usual because nix-cache might be down

            '
      - name: Install Attic
        run: nix profile add .#attic
      - name: Set up Attic cache
        uses: ryanccn/attic-action@v0.4.1
        with:
          cache: nixos-config
          endpoint: https://nix-cache.niols.fr/
          token: ${{ secrets.ATTIC_TOKEN }}
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Deploy machines
        run: "echo \"${{ secrets.DEPLOY_KEY }}\" > deploy-key\nchmod 600 deploy-key\nssh-agent bash -c\
          \ '\n  ssh-add deploy-key\n  export NIX_CONFIG=$(cat nix-config)\n  nix run .#rebuild -- deploy\
          \ --action boot --reboot --flake cwd --log raw\n'\n"
  home:
    name: Home
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: 'access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

            download-attempts = 10 # more than usual because nix-cache might be down

            '
      - name: Install Attic
        run: nix profile add .#attic
      - name: Set up Attic cache
        uses: ryanccn/attic-action@v0.4.1
        with:
          cache: nixos-config
          endpoint: https://nix-cache.niols.fr/
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Build Home configuration “${{ matrix.home }}”
        run: nix build .#homeConfigurations.${{ matrix.home }}.activationPackage --impure --print-build-logs
    strategy:
      fail-fast: false
      matrix:
        include:
          - home: headless-work
  nixos:
    name: NixOS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: 'access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

            download-attempts = 10 # more than usual because nix-cache might be down

            '
      - name: Install Attic
        run: nix profile add .#attic
      - name: Set up Attic cache
        uses: ryanccn/attic-action@v0.4.1
        with:
          cache: nixos-config
          endpoint: https://nix-cache.niols.fr/
          token: ${{ secrets.ATTIC_TOKEN }}
      - if: ${{ contains(fromJSON('["ahlaya","gromit"]'), matrix.nixos) }}
        name: Free some extra space
        run: 'echo ''Available storage before:''

          sudo df -h

          echo

          sudo rm -rf /usr/share/dotnet

          sudo rm -rf /usr/local/lib/android

          sudo rm -rf /opt/ghc

          sudo rm -rf /opt/hostedtoolcache/CodeQL

          echo ''Available storage after:''

          sudo df -h

          echo

          '
      - if: ${{ contains(fromJSON('["orianne"]'), matrix.nixos) }}
        name: Set up emulation layer
        run: 'echo "system = aarch64-linux" > nix-config

          sudo apt-get update -y && sudo apt-get install -y qemu-user-static

          '
      - name: Build NixOS configuration “${{ matrix.nixos }}”
        run: 'export NIX_CONFIG=$(cat nix-config)

          nix build .#nixosConfigurations.${{ matrix.nixos }}.config.system.build.toplevel --print-build-logs

          '
      - name: Remaining space
        run: 'echo ''Available storage:''

          sudo df -h

          '
    strategy:
      fail-fast: false
      matrix:
        nixos:
          - ahlaya
          - anastasia
          - gromit
          - helga
          - orianne
  summarise:
    if: always()
    name: Summarise
    needs:
      - check
      - home
      - nixos
      - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: check, home, nixos, deploy
          jobs: ${{ toJSON(needs) }}
name: CI
'on':
  pull_request: {}
  push:
    branches:
      - main
