name: Flake update

on:
  workflow_dispatch:  # manual triggering
  schedule:
    - cron: '0 4 * * MON'  # weekly, 04:00 on Monday
  repository_dispatch:
    types: [bump-dancelor]  # when Dancelor changes

jobs:

  flake-update:
    name: Bump all dependencies

    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'repository_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        id: update
        uses: determinatesystems/update-flake-lock@v27
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "Bump flake dependencies"

      - name: Set up auto-merge
        run: "gh pr merge --auto --squash ${{ steps.update.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}

  flake-update-dancelor:
    name: Bump Dancelor

    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch'
         && github.event.action == 'bump-dancelor' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        id: update
        uses: determinatesystems/update-flake-lock@v27
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          inputs: dancelor
          pr-title: "Bump Dancelor"

      - name: Set up auto-merge
        run: "gh pr merge --auto --squash ${{ steps.update.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
